### PR TITLE
Update init_otus.c

### PR DESCRIPTION
**Pull request by lennon2298**

### CODE REVIEW

**Comment by sultanqasim** [comment]
Could you rebase this off the current tree? I like to have linear history where possible. Thanks.

**Comment by lennon2298** [comment]
sorry, but i didn't get what you mean. Actually i'm new to GitHub so sorry.

**Comment by sultanqasim** [comment]
That's fine, I'll show you how. You can read a bit more about it on the net if you'd like, it's good to learn about git. Rebasing is an alternative to merging. When you rebase, you update your tree to the tree you are rebasing off of (mine), and then reapply your commits on top of the rebased tree. In this case, I had already added a case for the XT1506 in my tree, but it was after you had forked my tree. My commit included the build number etc for the XT1506, but didn't include the last two lines in yours. When you rebase, you will see that that your commit will change to adding just two lines.

To rebase, you must first add my repository as a remote. To do this, run the following command inside your git repository:
git remote add upstream https://github.com/sultanqasim/android_device_motorola_otus.git

Next, you need to fetch my version of the respository:
git fetch upstream cm-12.1

Now rebase your branch off mine:
git rebase FETCH_HEAD

This will modify your commit to only add the two new lines. Now, since you have changed a commit that was already pushed, you will have to force push it:
git push -f origin cm-12.1

**Comment by lennon2298** [comment]
when i tried to force push the commit it showed this error
remote: Permission to sultanqasim/android_device_motorola_otus.git denied to raghu3097.
fatal: unable to access 'https://github.com/sultanqasim/android_device_motorola_otus/': The requested URL returned error: 403

**Comment by sultanqasim** [comment]
It is saying that you don't have permission to push to my repository. You should have permission to push to your own fork though. I assumed that the remote "origin" points to your own fork. Are you sure you entered the last command correctly? If origin indeed points to my repository rather than your fork, you can add a remote for your fork and push to it:
git remote add raghu git@github.com:raghu3097/android_device_motorola_otus.git
git push -f raghu cm-12.1

BTW, What do you get when you run:
git remote -v

**Pull request closed without merging**
